### ISSUE TITLE
Neue Markierung lässt sich nicht anlegen

### ISSUE THREAD

**Issue by hartenthaler** [huhwt/huhwt-tsm#6]
Ich habe in der tsm-Ansicht von der bislang aktiven Kennung TAG auf die zweite Kennung ONTOLOGIE umgeschaltet. Dann wollte ich eine neue Markierung erzeugen. Das Dialogfenster öffnet sich mit der passenden Vorgabe "ONTOLOGIE: ". Dahinter gebe ich z.B. test ein. Nach dem Abschicken kommt die Fehlermeldung "Es gibt ein Problem ... Die Markierung muss mit ONTOLOGIE: beginnen". Das tut sie ja aber.

![Screenshot (25)](https://github.com/huhwt/huhwt-tsm/assets/6324175/109b5d2d-c6ee-4b4a-8669-012ad94b8f3e)

**Comment by huhwt** [comment]
Da tippe ich mal darauf, dass in den Preferences 'TAG, ONTOLOGIE' steht ... Die Markierungen müssen ohne Leerzeichen aneinandergereiht werden. Um das Problem zu beheben, die Notiz bearbeiten - Notizen-Liste, Notiz auswählen, bearbeiten, führendes Leerzeichen entfernen - und in den Preferences ebenfalls das Leerzeichen entfernen. Ich werde das Coding entsprechend anpassen, so die Preferences korrekt gefüllt werden.

**Comment by hartenthaler** [comment]
Genau das war die Ursache! Ja, ich fände es gut, wenn beim Speichern der Präferenzen aus ", " ein "," werden würde.
